POST {{domain}}/api/v1/user
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "username" : "test",
  "password" : "123456789"
}
###
GET {{domain}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{authToken}}
###